Add patch from robs@users.sf.net:
Adds support for FLAC input and output (if FLAC libs
are available).

Allows vorbis encoding quality to be specified.

Warns that with mp3, encoding quality cannot be
specified.

Fixes a bug in deemph that prevented its use with
ogg, flac, etc.

A couple of const-correctness fixes that were needed
for flac.

Documentation for the above.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1271,6 +1271,7 @@ Optional Features:
   --disable-oss-dsp       Disable detection of OSS
   --disable-sun-audio     Disable detection of SUN-style audio
   --disable-ogg-vorbis    Disable detection of Ogg Vorbis
+  --disable-flac    Disable detection of FLAC
   --disable-mad           Disable detection of MAD (MP3 Audio Decoder)
   --disable-lame          Disable detection of LAME (LAME Ain't an MP3 Encoder)
   --disable-samplerate    Detection of libsamplerate (aka Secret Rabbit Code)
@@ -1793,6 +1794,14 @@ if test "${enable_ogg_vorbis+set}" = set; then
   enableval=$enable_ogg_vorbis; enable_ogg_vorbis=$enableval
 else
   enable_ogg_vorbis=yes
+fi
+
+
+# Check whether --enable-flac was given.
+if test "${enable_flac+set}" = set; then
+  enableval=$enable_flac; enable_flac=$enableval
+else
+  enable_flac=yes
 fi
 
 
@@ -5418,6 +5427,263 @@ _ACEOF
 
 else
   enable_ogg_vorbis=no
+fi
+
+    fi
+fi
+
+
+if test "$enable_flac" = yes
+then
+    if test "${ac_cv_header_FLAC_file_encoder_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for FLAC/file_encoder.h" >&5
+echo $ECHO_N "checking for FLAC/file_encoder.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_FLAC_file_encoder_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_FLAC_file_encoder_h" >&5
+echo "${ECHO_T}$ac_cv_header_FLAC_file_encoder_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking FLAC/file_encoder.h usability" >&5
+echo $ECHO_N "checking FLAC/file_encoder.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <FLAC/file_encoder.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking FLAC/file_encoder.h presence" >&5
+echo $ECHO_N "checking FLAC/file_encoder.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <FLAC/file_encoder.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: FLAC/file_encoder.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: FLAC/file_encoder.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FLAC/file_encoder.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: FLAC/file_encoder.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: FLAC/file_encoder.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: FLAC/file_encoder.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FLAC/file_encoder.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: FLAC/file_encoder.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FLAC/file_encoder.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: FLAC/file_encoder.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FLAC/file_encoder.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: FLAC/file_encoder.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FLAC/file_encoder.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: FLAC/file_encoder.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: FLAC/file_encoder.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: FLAC/file_encoder.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## --------------------------------------------- ##
+## Report this to cbagwell@users.sourceforge.net ##
+## --------------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for FLAC/file_encoder.h" >&5
+echo $ECHO_N "checking for FLAC/file_encoder.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_FLAC_file_encoder_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_FLAC_file_encoder_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_FLAC_file_encoder_h" >&5
+echo "${ECHO_T}$ac_cv_header_FLAC_file_encoder_h" >&6; }
+
+fi
+if test $ac_cv_header_FLAC_file_encoder_h = yes; then
+  found_flac=yes
+else
+  enable_flac=no
+fi
+
+
+    if test "$found_flac" = yes
+    then
+        { echo "$as_me:$LINENO: checking for FLAC__file_encoder_new in -lFLAC" >&5
+echo $ECHO_N "checking for FLAC__file_encoder_new in -lFLAC... $ECHO_C" >&6; }
+if test "${ac_cv_lib_FLAC_FLAC__file_encoder_new+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lFLAC  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char FLAC__file_encoder_new ();
+int
+main ()
+{
+return FLAC__file_encoder_new ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_FLAC_FLAC__file_encoder_new=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_FLAC_FLAC__file_encoder_new=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_FLAC_FLAC__file_encoder_new" >&5
+echo "${ECHO_T}$ac_cv_lib_FLAC_FLAC__file_encoder_new" >&6; }
+if test $ac_cv_lib_FLAC_FLAC__file_encoder_new = yes; then
+  LIBS="-lFLAC $LIBS"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBFLAC 1
+_ACEOF
+
+else
+  enable_flac=no
 fi
 
     fi
@@ -9520,6 +9786,7 @@ echo "ALSA Driver.......................   $enable_alsa_dsp"
 echo "OSS Driver........................   $enable_oss_dsp"
 echo "SUN /dev/audio....................   $enable_sun_audio"
 echo "Ogg Vorbis support................   $enable_ogg_vorbis"
+echo "FLAC support......................   $enable_flac"
 echo "MAD MP3 Decoder...................   $enable_mad"
 echo "LAME MP3 Encoder..................   $enable_lame"
 echo "Secret Rabbit Code resampling.....   $enable_samplerate"
